### ISSUE TITLE
Preparing first release

### ISSUE THREAD

**Issue by slaterx** [moleculer-go/moleculer#10]
Listing here the required tasks to make first release:

- Support go modules (https://github.com/golang/go/wiki/Modules#new-concepts)
- Setup version numbering (https://semver.org/)
- Create documentation - probably on doc.go (https://blog.golang.org/godoc-documenting-go-code)

**Comment by giang12** [comment]
do you have a timeline for 1st stable release? 
thanks and congrats!

**Comment by slaterx** [comment]
We should be releasing by the end of April.

**Comment by dehypnosis** [comment]
really looking forward to this!!!

**Comment by icebob** [comment]
Good job!

**Comment by pentateu** [comment]
@dehypnosis and @giang12 thank you for your interest. We are very keen to receive feedback. Please let us know what you think about it and your own suggestions. You should be able to run the examples as a starting point. That is missing is a few small features (action param validations, cache, CLI) and the best way to address these features is to starting to write apps using to decide on the best API for it. So we are focused on creating the examples now and alongside finishing these last couple of features.
