### ISSUE TITLE
does it support namespace ？

### ISSUE THREAD

**Issue by roytan883** [moleculer-go/moleculer#67]
**Is your feature request related to a problem? Please describe.**
does it support namespace ？

**Comment by slaterx** [comment]
Not at this point. Could you please describe your use case for it?

**Comment by roytan883** [comment]
it is standard in moleculer protocol. group many different service to few namespace.

**Comment by pentateu** [comment]
Namespaces is not implemented yet. If you need it we can consider adding to the current scope (beta release). 
Let us know more of your use case and feedback on moleculer go.

**Comment by roytan883** [comment]
Its about node info sync and separate high level services. If all service nodes running on the same namespace, the moleculer `HEARTBEAT` and node information are mixed and net traffic heavy. 

Consider V1 services has 30 nodes, and V2 services has 10 nodes. Most of V2 nodes no need call V1 nodes, then it should not communicate V1 nodes. Only the V1-V2-bridge node need have both two namespace.

**Comment by yacineb** [comment]
We absolutely need this !

**Comment by pentateu** [comment]
@yacineb @roytan883  use version v0.2.4 or above for namespace support.
