### ISSUE TITLE
MoleculerJS v0.14.x and protocol V4 compatibility.

### ISSUE THREAD

**Issue by dehypnosis** [moleculer-go/moleculer#71]
Hi guys, I hope all things are going well. I wish there is a definite goal toward MoleculerJS v0.14.x and protocol V4 and further compatibility. But I know there is not enough time for this currently.

So I want to suggest that how about to publicize moleculer-go project and gather some contributors from 'moleculer' community?

MolecuerJS has released v0.14.0-beta1 in July, and now -beta3.
Also now Moleculer protocol has been arrived to V4. [ref.](https://github.com/moleculerjs/moleculer/tree/next/docs)

I think the time has come to keep up with moleculerJS. I know making an open source polyglot is not easy but just can't stop worrying that it would be too far apart from the moleculerJS specially in core modules (transit, metrics, tracing, protocol, etc ...)
When this problem is resolved, I think moleculer-go version API gateway and other duplicate modules could be non-mandatory work .

For example, moleculer-web released a new features recently.. [ref.](https://github.com/moleculerjs/moleculer-web/releases) and many of moleculer users already have been using it. I think inducing developers to Golang version API Gateway would be hard and will not be economic.

And me and others are working on so many other moleculer modules, We can just embrace all the MoleculerJS module/services. I don't want to be rude and I am not disregarding your amzaing works, but I think moleculer-go can focus on 'moleculer' itself rather than adaptive module and plugins which have replacements. Because as you know MSA can accept Node.js and Golang together!

I know you guys working too hard for moleculer-go and whole community. As a big fan of Moleculer and Golang, I really appreciate to it. Also I hope that the time when Golang users get noticed about the power of moleculer comes faster. I think moleculer-go should be ready for that.

So, are you in #moleculer Discord channel? It would be amazing if you open and manage #moleculer-go channel. I want to discuss about it more and hope you have same idea. Also please tell me anything I can help, now I have a little time for contribution.

**Comment by pentateu** [comment]
Hi again,

We appreciate your support.

Out goal is to be community driven, so we will consider your request to prioritise moleculer v.0.14 compatibility. 
Yes it is also our goal to be 100% compatible with Moleculer JS. I also wrote tons of Moleculer JS code and I love it.
On release v0.1.1 back in May, on your request :) and after you did a good deal of investigation yourself it only took me a few days to adjust with molecular 0.13. Now that I have all the testing should be much easier.

My current focus is on writing applications and examples. Exactly so we can promote and attract more people. Developers love code, so after the examples I need to work on docs also.

Writing real apps on top of it is what allows me to refine it and feel the gaps, which is what I;m doing at the moment. Right now I'm filling this gap -> https://github.com/moleculer-go/cqrs/tree/feat/snapshot

After that I'll work on: https://github.com/moleculer-go/moleculer/issues/61

I have been busy with a contract, but now I'm getting back at working on this regularly again.

**Comment by dehypnosis** [comment]
Thank you so much for the your sincere comment.

Yes, You are right. I was not thinking straight. As you said, sophisticated application shall be need to enhance the moleculer library.

I have been busy with a new job too. And also leaved all the moleculer things behind the ex-company. And here in the new company, I have more decision making authority. And so I'm now trying to contribute to moleculer community while working for our company.

So after release v0.1.1, I haven't enough chance to check it deeply with moleculer-js. But I'm planning to use moleculer-go partially for DNN related service soon.

I will follow your work and will try to contribute, at least, reporting the compatibility bugs.
Thank you so much for your work again^^ And Good luck!

**Comment by ujwal-setlur** [comment]
I am seriously considering moleculer for my upcoming project since it supports the core technologies (NATS, GraphQL, etc) that I had chosen, and I will be using both JS and Go, so this combination is what I need. Do we know if there are breaking issues going from V3->V4? I don't have too much time, but I am happy to contribute where I can.

**Comment by pentateu** [comment]
https://github.com/moleculer-go/moleculer/tree/v0.3.0

Please test more carefully and let me know if you find any issues.

**Comment by ujwal-setlur** [comment]
Hey, this is great news. I had decided to proceed with just the original node version, but this will certainly give me options. I’ll check it out. Thanks!
