### ISSUE TITLE
Protocol v4 not supported

### ISSUE THREAD

**Issue by irzhywau** [moleculer-go/moleculer#90]
**Describe the bug**
I'm using nodejs moleculer implementation `v0.14` and the protocol version is `4`. When I tried to run moleculer-go with the same `NATS` server it just reports `ProtocolVersionMismatch` error which I think is normal as for instance, this go implementation is still on version `3` of the protocol

**To Reproduce**
Run a moleculer js (use docker to make it faster, and expose the NATS port to the host), then run the example in the readme of this repo -> `ProtocolVersionMissmatchError`

**Expected behavior**
Protocol version `4` supported

**Additional context**
Maybe a comparison of both protocol should be established first in order to have a good background of what should be done. Also I'm not sure if all pending issues are required or not.

I'm willing to make progress on this section if anyone can help me to get started in better condition

**Comment by pentateu** [comment]
https://github.com/moleculer-go/moleculer/tree/v0.3.0

Please test more carefully and let me know if you find any issues.
